"use client";

import AgentCard from "./AgentCard";

const agents = [
  {
    id: 1,
    name: "ai.apt",
    avatar: "/AIapt.jpg",
    walletAddress: "0x1234...5678",
    weeklyReturn: 12.5,
    managedFunds: 30500,
    userCount: 500,
    twitterHandle: "AIapt",
    description:
      "AI trading system using spot grids, trends, and event triggers with real-time data and risk controls, targeting 10%-15% monthly returns.",
    riskLevel: "Low",
  },
  {
    id: 2,
    name: "Crypto Wizard",
    avatar: "/CryptoWizard.jpg",
    walletAddress: "0xabcd...efgh",
    weeklyReturn: 18.7,
    managedFunds: 2500000,
    userCount: 750,
    twitterHandle: "CryptoWizard",
    description: "Expert in altcoin trading and DeFi protocols. Moderate risk with high returns.",
    riskLevel: "Medium",
  },
  {
    id: 3,
    name: "DeFi Master",
    avatar: "/DeFiMaster.jpg",
    walletAddress: "0x9876...5432",
    weeklyReturn: 15.3,
    managedFunds: 1750000,
    userCount: 620,
    twitterHandle: "DeFiMaster",
    description: "Focuses on liquidity provision and yield optimization in DeFi ecosystems.",
    riskLevel: "Medium",
  },
  {
    id: 4,
    name: "Leverage King",
    avatar: "/LeverageKing.jpg",
    walletAddress: "0xfedc...ba98",
    weeklyReturn: 22.1,
    managedFunds: 3000000,
    userCount: 400,
    twitterHandle: "LeverageKing",
    description: "Focuses on leveraged trading, maximizing both risks and rewards with precise market timing.",
    riskLevel: "High",
  },
  {
    id: 5,
    name: "Trend Surfer",
    avatar: "/TrendSurfer.jpg",
    walletAddress: "0x2468...1357",
    weeklyReturn: 14.8,
    managedFunds: 1200000,
    userCount: 550,
    twitterHandle: "TrendSurfer",
    description: "Excels in trend following and momentum trading across various cryptocurrencies.",
    riskLevel: "Medium",
  },
  {
    id: 6,
    name: "Arbitrage Pro",
    avatar: "/ArbitragePro.jpg",
    walletAddress: "0x1357...2468",
    weeklyReturn: 10.2,
    managedFunds: 5000000,
    userCount: 300,
    twitterHandle: "ArbitragePro",
    description: "Focuses on cross-exchange arbitrage opportunities. Low-risk, consistent returns.",
    riskLevel: "Low",
  },
  {
    id: 7,
    name: "NFT Flipper",
    avatar: "/NFTFlipper.jpg",
    walletAddress: "0xaaaa...bbbb",
    weeklyReturn: 25.6,
    managedFunds: 800000,
    userCount: 200,
    twitterHandle: "NFTFlipper",
    description: "Specializes in NFT trading and flipping. High volatility, potential for large gains.",
    riskLevel: "High",
  },
  {
    id: 8,
    name: "Staking Specialist",
    avatar: "/StakingSpecialist.jpg",
    walletAddress: "0xcccc...dddd",
    weeklyReturn: 8.9,
    managedFunds: 10000000,
    userCount: 1500,
    twitterHandle: "StakingSpecialist",
    description: "Focuses on staking and validator node operations. Steady, low-risk returns.",
    riskLevel: "Low",
  },
  {
    id: 9,
    name: "Options Trader",
    avatar: "/OptionsTrader.jpg",
    walletAddress: "0xeeee...ffff",
    weeklyReturn: 20.3,
    managedFunds: 1500000,
    userCount: 350,
    twitterHandle: "OptionsTrader",
    description: "Skilled in crypto options trading, aiming for a steady balance of risks and rewards.",
    riskLevel: "Medium",
  },
  {
    id: 10,
    name: "Metaverse Investor",
    avatar: "/MetaverseInvestor.jpg",
    walletAddress: "0x1111...2222",
    weeklyReturn: 17.5,
    managedFunds: 2000000,
    userCount: 600,
    twitterHandle: "MetaverseInvestor",
    description: "Invests in metaverse tokens and virtual real estate, tapping into the growing digital economy.",
    riskLevel: "Medium",
  },
  {
    id: 11,
    name: "AI Trading Bot",
    avatar: "/AITradingBot.jpg",
    walletAddress: "0x3333...4444",
    weeklyReturn: 16.8,
    managedFunds: 4000000,
    userCount: 800,
    twitterHandle: "AITradingBot",
    description: "Uses advanced AI for high-frequency trading, profiting from fast market movements.",
    riskLevel: "Medium",
  },
  {
    id: 12,
    name: "Long-Term HODLer",
    avatar: "/Long-TermHODLer.jpg",
    walletAddress: "0x5555...6666",
    weeklyReturn: 7.2,
    managedFunds: 15000000,
    userCount: 2000,
    twitterHandle: "LongTermHODLer",
    description: "Focuses on long-term value investing in established cryptocurrencies.",
    riskLevel: "Low",
  },
];

export default function AgentList() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {agents.map((agent) => (
        <AgentCard key={agent.id} agent={agent} />
      ))}
    </div>
  );
}
